
services:
  frontend:
    build:
      context: ./front-todo-teste-reverb
    container_name: next-app
    ports:
      - '3000:3000'
    depends_on:
      - api

  api:
    build:
      context: ./backt-todo-teste-reverb
    container_name: express-api
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: docker
    depends_on:
      - db
    env_file: ./backt-todo-teste-reverb/.env.docker

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresadmin
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: